#!/bin/bash

NC="\033[0m"
LIGHTBLUE="\033[38;5;45m"
PURPLE="\033[38;5;165m"
LIGHTGREEN="\033[38;5;47m"

# Exit with non-zero status if any of the following commands fail
set -e

cd app

# Run prettier + eslint
npm run lint
npm run style
